export const projects = [
    {
        id: 1,
        judul: "Kurnia Rental",
        keterangan: "UI website rental mobil dengan desain modern dan responsif.",
        gambar: "/kurniarental.png",
        tech: ["Next.Js", "TypeScript", "Tailwind"],
        kategori: "ui",
    },
    {
        id: 2,
        judul: "Kovfee",
        keterangan: "Website coffeshop dengan menu interaktif dan sistem pemesanan.",
        gambar: "/kofvee.png",
        tech: ["React.Js", "Javascript", "Tailwind", "Golang"],
        kategori: "fullstack",
    },
    {
        id: 3,
        judul: "Miracle Mates",
        keterangan: "Website toko distro dengan katalog produk dan desain modern.",
        gambar: "/miracle.png",
        tech: ["React", "TypeScript", "Tailwind"],
        kategori: "web",
    },
    {
        id: 4,
        judul: "Booking Pilates",
        keterangan: "Platform booking kelas pilates dengan sistem reservasi online.",
        gambar: "/pilates.png",
        tech: ["Next.Js", "TypeScript", "Tailwind", "Golang", "Prisma"],
        kategori: "fullstack",
    },
    {
        id: 5,
        judul: "Konsultan Pajak",
        keterangan: "Website company profile konsultan pajak dan layanan profesional.",
        gambar: "/konsultan2.png",
        tech: ["Wordpress"],
        kategori: "web",
    },
    {
        id: 6,
        judul: "KIS Kontraktor",
        keterangan: "Website perusahaan kontraktor dengan portofolio proyek.",
        gambar: "/web-kontraktor.png",
        tech: ["React", "Javascript", "Tailwind"],
        kategori: "web",
    },
    {
        id: 7,
        judul: "KUN Armada Nusantara",
        keterangan: "Website layanan armada transportasi dan katalog kendaraan.",
        gambar: "/KurniaUsaha.png",
        tech: ["React", "Javascript", "Tailwind"],
        kategori: "web",
    },
    {
        id: 8,
        judul: "Software House",
        keterangan: "Website software house dengan layanan dan portofolio proyek.",
        gambar: "/riqztech copy.png",
        tech: ["Next.Js", "Typescript", "Tailwind"],
        kategori: "web",
    },
    {
        id: 9,
        judul: "Dashboard App",
        keterangan: "Dashboard interaktif untuk monitoring dan visualisasi data.",
        gambar: "/dashboard.png",
        tech: ["React", "TypeScript"],
        kategori: "ui",
    },
    {
        id: 10,
        judul: "Islamic.WO",
        keterangan: "Website wedding organizer islami dengan paket layanan.",
        gambar: "/alifatimah.png",
        tech: ["Wordpress"],
        kategori: "web",
    },
    {
        id: 11,
        judul: "Reservation Hotel",
        keterangan: "Website reservasi hotel dengan sistem booking kamar.",
        gambar: "/booking-hotel.png",
        tech: ["Next.Js", "TypeScript", "Tailwind", "Golang", "Prisma"],
        kategori: "fullstack",
    },
    {
        id: 12,
        judul: "Screamous T-Shirt",
        keterangan: "Website brand fashion dengan katalog dan fitur belanja.",
        gambar: "/t-shirt.png",
        tech: ["React.Js", "Javascript", "Tailwind"],
        kategori: "web",
    },
    {
        id: 13,
        judul: "Undangan Digital Responsive",
        keterangan: "Website undangan digital dengan fitur RSVP responsif.",
        gambar: "/undangan.png",
        tech: ["Next.Js", "TypeScript", "Tailwind"],
        kategori: "web",
    },
]