export const projects = [
  {
    id: 1,
    judul: "Kurnia Rental",
    keterangan: "UI website rental mobil dengan desain modern dan responsif.",
    gambar: "/kurniarental.png",
    tech: ["Next.Js", "TypeScript", "Tailwind"],
    kategori: "ui",
  },
  {
    id: 2,
    judul: "Kovfee",
    keterangan:
      "Website coffeshop dengan menu interaktif dan sistem pemesanan.",
    gambar: "/kofvee.png",
    tech: ["React.Js", "Javascript", "Tailwind", "Golang"],
    kategori: "fullstack",
  },
  {
    id: 3,
    judul: "Miracle Mates",
    keterangan: "Website toko distro dengan katalog produk dan desain modern.",
    gambar: "/miracle.png",
    tech: ["React", "TypeScript", "Tailwind"],
    kategori: "web",
  },
  {
    id: 4,
    judul: "Booking Pilates",
    keterangan:
      "Platform booking kelas pilates dengan sistem reservasi online.",
    gambar: "/pilates.png",
    tech: ["Next.Js", "TypeScript", "Tailwind", "Golang", "Prisma"],
    kategori: "fullstack",
  },
  {
    id: 5,
    judul: "Konsultan Pajak",
    keterangan:
      "Website company profile konsultan pajak dan layanan profesional.",
    gambar: "/konsultan2.png",
    tech: ["Wordpress"],
    kategori: "web",
  },
  {
    id: 6,
    judul: "KIS Kontraktor",
    keterangan: "Website perusahaan kontraktor dengan portofolio proyek.",
    gambar: "/web-kontraktor.png",
    tech: ["React", "Javascript", "Tailwind"],
    kategori: "web",
  },
  {
    id: 7,
    judul: "KUN Armada Nusantara",
    keterangan: "Website layanan armada transportasi dan katalog kendaraan.",
    gambar: "/KurniaUsaha.png",
    tech: ["React", "Javascript", "Tailwind"],
    kategori: "web",
  },
  {
    id: 8,
    judul: "Software House",
    keterangan: "Website software house dengan layanan dan portofolio proyek.",
    gambar: "/riqztech copy.png",
    tech: ["Next.Js", "Typescript", "Tailwind"],
    kategori: "web",
  },
  {
    id: 9,
    judul: "Dashboard App",
    keterangan: "Dashboard interaktif untuk monitoring dan visualisasi data.",
    gambar: "/dashboard.png",
    tech: ["React", "TypeScript"],
    kategori: "ui",
  },
  {
    id: 10,
    judul: "Islamic.WO",
    keterangan: "Website wedding organizer islami dengan paket layanan.",
    gambar: "/alifatimah.png",
    tech: ["Wordpress"],
    kategori: "web",
  },
  {
    id: 11,
    judul: "Reservation Hotel",
    keterangan: "Website reservasi hotel dengan sistem booking kamar.",
    gambar: "/booking-hotel.png",
    tech: ["Next.Js", "TypeScript", "Tailwind", "Golang", "Prisma"],
    kategori: "fullstack",
  },
  {
    id: 12,
    judul: "Screamous T-Shirt",
    keterangan: "Website brand fashion dengan katalog dan fitur belanja.",
    gambar: "/t-shirt.png",
    tech: ["React.Js", "Javascript", "Tailwind"],
    kategori: "web",
  },
  {
    id: 13,
    judul: "Jonathan & Sherla",
    keterangan:
      "Undangan pernikahan digital elegan dengan animasi dan fitur RSVP online.",
    gambar: "/undangan.png",
    tech: ["Next.Js", "TypeScript", "Tailwind"],
    kategori: "web",
  },
  {
    id: 14,
    judul: "Amadeus & Michelle",
    keterangan:
      "Website undangan pernikahan romantis dengan galeri foto dan countdown hari H.",
    gambar: "/amadeus.png",
    tech: ["Next.Js", "TypeScript", "Tailwind"],
    kategori: "web",
  },
  {
    id: 15,
    judul: "Uun Friends",
    keterangan:
      "Undangan digital modern dengan tampilan minimalis dan konfirmasi kehadiran.",
    gambar: "/uun.png",
    tech: ["Next.Js", "TypeScript", "Tailwind"],
    kategori: "web",
  },
  {
    id: 16,
    judul: "Ivan & Wina",
    keterangan:
      "Website pernikahan interaktif dengan fitur ucapan dan live countdown.",
    gambar: "/ivan.png",
    tech: ["Next.Js", "TypeScript", "Tailwind"],
    kategori: "web",
  },
  {
    id: 17,
    judul: "Jeanette & Nicholas",
    keterangan:
      "Undangan digital premium dengan desain mewah dan sistem RSVP real-time.",
    gambar: "/jeanette.png",
    tech: ["Next.Js", "TypeScript", "Tailwind"],
    kategori: "web",
  },
  {
    id: 18,
    judul: "Fani & Akbar",
    keterangan:
      "Website undangan pernikahan dengan tema floral dan fitur peta lokasi acara.",
    gambar: "/fani.png",
    tech: ["Next.Js", "TypeScript", "Tailwind"],
    kategori: "web",
  },
  {
    id: 19,
    judul: "Galih & Vio",
    keterangan:
      "Undangan digital responsif dengan musik latar dan animasi scroll yang halus.",
    gambar: "/galih.png",
    tech: ["Next.Js", "TypeScript", "Tailwind"],
    kategori: "web",
  },
  {
    id: 20,
    judul: "Angela & Hendy",
    keterangan:
      "Website undangan pernikahan elegan dengan desain klasik dan fitur RSVP lengkap.",
    gambar: "/Angela-Hendy.png",
    tech: ["Next.Js", "TypeScript", "Tailwind"],
    kategori: "web",
  },
  {
    id: 21,
    judul: "Keny & Destiny",
    keterangan:
         "Undangan pernikahan digital bertema romantis dengan animasi halus dan fitur RSVP interaktif.",
    gambar: "/keny-destiny.png",
    tech: ["Next.Js", "TypeScript", "Tailwind"],
    kategori: "web",
  },
  {
    id: 22,
    judul: "Jacky & Jessie",
    keterangan:
    "Website undangan pernikahan modern dengan galeri foto estetik dan countdown menuju hari H.",
    gambar: "/jacky-jessie.png",
    tech: ["Next.Js", "TypeScript", "Tailwind"],
    kategori: "web",
  },
  {
    id: 23,
    judul: "Jusuf & Evelyn",
    keterangan:
    "Undangan digital pernikahan dengan desain elegan, musik latar, dan sistem konfirmasi kehadiran online.",
    gambar: "/jusuf-evelyn.png",
    tech: ["Next.Js", "TypeScript", "Tailwind"],
    kategori: "web",
  },
];
