export const projects = [
    {
        id:1,
        judul: "Kurnia Rental",
        keterangan: "Website Rental Mobil dengan Sistem Admin dan Range Harga untuk memilah Armada",
        gambar: "/riqztech copy.png",
        tech: ["React", "TypeScript", "Storybook", "CSS Modules"],
        kategori: "ui",
    },
    {
        id:2,
        judul: "Kurnia Rental",
        keterangan: "Website Rental Mobil dengan Sistem Admin dan Range Harga untuk memilah Armada",
        gambar: "/kurniarental.png",
        tech: ["React", "TypeScript", "Storybook", "CSS Modules"],
        kategori: "ui",
    },
    {
        id:3,
        judul: "Kurnia Rental",
        keterangan: "Website Rental Mobil dengan Sistem Admin dan Range Harga untuk memilah Armada",
        gambar: "/riqztech copy.png",
        tech: ["React", "TypeScript", "Storybook", "CSS Modules"],
        kategori: "web",
    },
    {
        id:4,
        judul: "Kurnia Rental",
        keterangan: "Website Rental Mobil dengan Sistem Admin dan Range Harga untuk memilah Armada",
        gambar: "/kurniarental.png",
        tech: ["React", "TypeScript", "Storybook", "CSS Modules"],
        kategori: "web",
    },
    {
        id:5,
        judul: "Kurnia Rental",
        keterangan: "Website Rental Mobil dengan Sistem Admin dan Range Harga untuk memilah Armada",
        gambar: "/riqztech copy.png",
        tech: ["React", "TypeScript", "Storybook", "CSS Modules"],
        kategori: "web",
    },
    {
        id:6,
        judul: "Kurnia Rental",
        keterangan: "Website Rental Mobil dengan Sistem Admin dan Range Harga untuk memilah Armada",
        gambar: "/kurniarental.png",
        tech: ["React", "TypeScript", "Storybook", "CSS Modules"],
        kategori: "web",
    },
]